#! /bin/sh

# keyboard
setxkbmap -layout latam &
xsetroot -cursor_name left_ptr &
sxhkd &

# desktop
feh --bg-scale ~/.config/mountainRice/wallpapers/adventure-altitude-clear-sky-633198.jpg &
polybar mountainRice &
dunst -config ~/.config/dunst/dunstrc &
picom --config ~/.config/picom.conf &

# utilities
udiskie -n -s &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
